---
# role: samba_ad
# file: tasks/main.yml

- name: SAMBA_AD | Configure domain directory objects and DNS
  ansible.builtin.import_tasks: directory.yml
  module_defaults:
    group/jomrr.samba.all:
      server: "{{ samba_ad_server }}"
      realm: "{{ samba_ad_realm | upper }}"
      bind_username: Administrator
      bind_password: "{{ samba_ad_admin_password }}"
