---
# role: samba_ad
# file: molecule/resources/playbooks/converge.yml

- name: SAMBA_AD | Converge directory objects
  hosts: all
  gather_facts: false
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
